language: go

go:
  - 1.12.x

addons:
  postgresql: "9.6"

install:
  - find . -type f -exec sed -i 's/Peripli\/service-manager/sm-ci\/service-manager/g' {} +
  - make prepare

services:
  - postgresql

jobs:
  include:
    - stage: "Tests"
      name: "Other Integration Tests"
      script:
        - make precommit-integration-tests-other
        - kill %1
    - stage: "Tests"
      name: "Broker Integration Tests"
      script:
        - travis_wait 20 make precommit-integration-tests-broker
        - kill %1
    - stage: "Tests"
      name: "OSB and Plugin Integration Tests"
      script:
        - make precommit-integration-tests-osb-and-plugin
        - kill %1
    - stage: "Tests"
      name: "Service Instance and Service Bindings Integration Tests"
      script:
        - travis_wait 30 make precommit-integration-tests-service-instance-and-binding
        - kill %1
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - make precommit-unit-tests
        - kill %1

env:
  - COVERALLS_PARALLEL=true

notifications:
  slack: openservicebrokerapi:KQo2QAC6LXeEeXPOemOXja48
  webhooks: https://coveralls.io/webhook
